# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31b2f02c5c2547f0db2c7501fbe98bff86b239adbc22b841379d5057167c1ce405737b5e7f408fc8084692088bffcc2a8f2a0e465815234c785b3e68f5506846

test:
  secret_key_base: be220b260652c4ded274f2009913311d23f17fc34399ff2240833df8506c2922159ef108e874b428e9fe3b6e377ae5bc465a595e9e5e34a06f37a289241cbd2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
